services:
   db:
      image: postgres:13
      restart: always
      environment:
         - POSTGRES_HOST_AUTH_METHOD=trust
         - POSTGRES_DB=the-safe
      ports: 
         - "${DB_PORT:-5432}:5432"
      env_file:
         - ../.env
      volumes:
         - the-safe-volume:${DOCKER_DATABASE_VOLUME:-/var/lib/postgresql/data}
volumes:
   the-safe-volume: